sudo: false
language: node_js

git:
  depth: 3

branches:
  only:
    - master
    - dev

node_js:
  - stable

env:
  secure: "Tkmfqa0XkXYHBZ2+SDLvQVkR5GvSk7i4Ckjkv8Up5K7uaDnTfyuAwo1fvsZOMZpG37q2zChh6rdv9AA9xPSi4T+j6i/nOHmHcxD0jSYa6luS9G9DeMdA3jiXn9Ba4dhkkjtPTzK7qXpFODtCHmDACi0HeZ7qrY1Y2+wk10vrHVUpSJI2UI2SHXzx7t3pewssXttYY5FIiIsUigbkZqYc5AvPfqtIRMw9gpeZR8ZNKy+kBAYnRrG+GZk9+gYEt8v/kxa4SDc4vQu6d7OdWdunhOf0Ryvp8ozF9XlGpiuYawmwHRMs2C2s/XbC4Yg+ZzuOLgEhQ2PFpN+BQSoYXTs9MlKvJL0O1ZOna0qcT/km4rojRhtNyiGk5b9P+ahHDQu4/0uJXa5g0Ocsrs6r4KSubONaqoOe0sUaIaJigh1TqNcqNICl61l3gIEZhLRJO20lb89ho2Kauzr15sEr1tcwYBsNe/sHXJ+2sj7OOhhtXqT0jJxWhFI33Gl14ylhr3a5y7XAI6zHWz+41stS4nryXzB90+iJ3Tg6OMigGX+MEMwNJSm2Fr25XBumFzPFAG1NDYPvGiEp7Et59tjO7bzeFtQJZ3StIJ3FZC6W2ZhL3TJUeVJpXP2J9o13vRfID+Gswep8Ux7qlR9+noGzIG16tI+z9+XJ+d/+Ek4DLI1xyYc="

before_script:
  # install dependencies
  - npm install -g gulp
  - npm install -g typescript
  - npm install -g tsd
  # download type definitions
  - tsd install -r -o --save-dev
  # compile typescript
  - tsc -p ./

script:
  # execute all tests & gen code coverage report
  - "./node_modules/karma/bin/karma start ./config/karma.js --single-run"

after_script:
  # send code coverage report to coveralls.io
  - "cat ./coverage/**/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

notifications:
  slack:
    secure: SdyPKvuTLB9AmBC8g8nt6w6Qc3XDoQ6ICpSyfM1TDNNC+KvIsxw0ahpx9AvpBDbXTZNdyzcmAtHjUOAXbrCbTA0/6+rDEDHYTat4ZNiRhSJoJPjpV3hzeCVxT47jnljGrmzEUV/AhlcMJOIrn2Z5v2MoFmGHqyuhpOJqsz1KgppPMGRrmUrH779EZng/n6+JFQbDmLlA87n7BjRgw7QyzkbQHBTdhrQbGmMa0TaKYkTmaigp1E5Zf15UTWxt5lB2bH/v18fnF3cU9FHArr4PKi90ypx8FkNEthaSBCHFTVbrN3DXjCNAhyrBiomkJC2ML1gbBC/fskMDgektWfuSXftQt8zGOeMOT/+cAtNCQ7cTQ2lZ4lizKd5/+t0CSXeiUIsVcKEkgiYXdBHwSTf7Qfj2Zrjwl23tSFIag/IBgjZm++5LmfhSkQN95A9xxXUQzlcfUK2snflwH3FnygEqvbTbmSuMGzp4piHIcwCcNkcmYl8vfrA31ks8mHg648k5LFemO+7kPlAoEccBLkWJ4UVqpKN786jz4qHXTljj50pHWJXfuigh2ueuKAWnerBi/jodA/8nmyLuKOetogDJs7i0484SQ/x2jRqj7zOTCXbh3TB0msOQZlfJ38oymrl8eLI2IrLSefD3+Pct/z1Emmz6WFALQpWKXROdt7EvGao=
